SELECT nombre FROM producto; -- Llista el nom de tots els productos que hi ha en la taula producto 
SELECT nombre, precio FROM producto; -- Llista els noms i els preus de tots els productos de la taula producto 
SELECT * FROM producto; -- Llista totes les columnes de la taula producto 
SELECT nombre, precio * 1.12 FROM producto; --  Llista el nom dels productos, el preu en euros i el preu en dòlars nord-americans (USD) 
SELECT nombre AS 'Nom del producte', precio AS Euros, precio * 1.12 AS 'Dolards nord-Americans' FROM producto; -- Llista el nom dels productos, el preu en euros i el preu en dòlars nord-americans. Utilitza els següents àlies per a les columnes: nom de producto, euros, dòlars nord-americans 
SELECT UPPER(nombre) FROM producto; -- Llista els noms i els preus de tots els productos de la taula producto, convertint els noms a majúscula 
SELECT LOWER(nombre) FROM producto; -- Llista els noms i els preus de tots els productos de la taula producto, convertint els noms a minúscula 
SELECT nombre, LEFT(UPPER(nombre),2) AS 'Dos primeras letras del fabricanta' FROM fabricante; -- Llista el nom de tots els fabricants en una columna, i en una altra columna obtingui en majúscules els dos primers caràcters del nom del fabricant 
SELECT nombre, round(precio,2) FROM producto; -- Llista els noms i els preus de tots els productos de la taula producto, arrodonint el valor del preu 
SELECT nombre, round(precio) FROM producto; -- Llista els noms i els preus de tots els productos de la taula producto, truncant el valor del preu per a mostrar-lo sense cap xifra decimal 
SELECT codigo_fabricante FROM producto;	-- Llista el codi dels fabricants que tenen productos en la taula producto.
SELECT DISTINCT codigo_fabricante FROM producto; -- Llista el codi dels fabricants que tenen productos en la taula producto, eliminant els codis que apareixen repetits 
SELECT nombre FROM fabricante ORDER BY nombre; -- Llista els noms dels fabricants ordenats de manera ascendent 
SELECT nombre FROM fabricante ORDER BY nombre DESC; -- Llista els noms dels fabricants ordenats de manera descendent 
SELECT nombre, precio FROM producto ORDER BY nombre, precio DESC; -- Llista els noms dels productos ordenats en primer lloc pel nom de manera ascendent i en segon lloc pel preu de manera descendent 
SELECT * FROM fabricante LIMIT 5; -- Retorna una llista amb les 5 primeres files de la taula fabricante 
SELECT * FROM fabricante LIMIT 3,2; -- Retorna una llista amb 2 files a partir de la quarta fila de la taula fabricante. La quarta fila també s'ha d'incloure en la resposta 
SELECT nombre, precio FROM producto ORDER BY precio LIMIT 1; -- Llista el nom i el preu del producto més barat. (Utilitzi solament les clàusules ORDER BY i LIMIT). NOTA: Aquí no podria usar MIN(preu), necessitaria GROUP BY
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1; -- Llista el nom i el preu del producto més car. (Utilitzi solament les clàusules ORDER BY i LIMIT). NOTA: Aquí no podria usar MAX(preu), necessitaria GROUP BY. 
SELECT nombre, codigo_fabricante FROM producto WHERE codigo_fabricante=2; -- Llista el nom de tots els productos del fabricant el codi de fabricant del qual és igual a 2 
SELECT producto.nombre, producto.precio, fabricante.nombre FROM producto INNER JOIN fabricante ON fabricante.codigo=producto.codigo_fabricante; -- Retorna una llista amb el nom del producte, preu i nom de fabricant de tots els productes de la base de dades 
SELECT producto.nombre, producto.precio, fabricante.nombre FROM producto INNER JOIN fabricante ON fabricante.codigo=producto.codigo_fabricante ORDER BY fabricante.nombre; -- Retorna una llista amb el nom del producte, preu i nom de fabricant de tots els productes de la base de dades. Ordeni el resultat pel nom del fabricador, per ordre alfabètic 
SELECT producto.codigo, producto.nombre, producto.codigo_fabricante, fabricante.nombre FROM producto INNER JOIN fabricante ON fabricante.codigo=producto.codigo_fabricante; -- Retorna una llista amb el codi del producte, nom del producte, codi del fabricador i nom del fabricador, de tots els productes de la base de dades 
SELECT producto.nombre, producto.precio, fabricante.nombre FROM producto INNER JOIN fabricante ON fabricante.codigo=producto.codigo_fabricante ORDER BY precio LIMIT 1; -- Retorna el nom del producte, el seu preu i el nom del seu fabricant, del producte més barat 
SELECT producto.nombre, producto.precio, fabricante.nombre FROM producto INNER JOIN fabricante ON fabricante.codigo=producto.codigo_fabricante ORDER BY precio DESC LIMIT 1; -- Retorna el nom del producte, el seu preu i el nom del seu fabricant, del producte més car 
SELECT producto.codigo, producto.nombre, producto.precio FROM producto INNER JOIN fabricante ON fabricante.codigo=producto.codigo_fabricante WHERE fabricante.nombre='Lenovo'; -- Retorna una llista de tots els productes del fabricador Lenovo. 
SELECT producto.codigo, producto.nombre, producto.precio FROM producto INNER JOIN fabricante ON fabricante.codigo=producto.codigo_fabricante WHERE fabricante.nombre='Crucial' AND producto.precio>200; -- Retorna una llista de tots els productes del fabricant Crucial que tinguin un preu major que 200€ 
SELECT producto.codigo, producto.nombre, producto.precio, fabricante.nombre FROM producto INNER JOIN fabricante ON fabricante.codigo=producto.codigo_fabricante WHERE fabricante.nombre='Asus' OR fabricante.nombre='Hewlett-Packard' OR fabricante.nombre='Seagate'; -- Retorna un llistat amb tots els productes dels fabricants Asus, Hewlett-Packardy Seagate. Sense utilitzar l'operador IN 
SELECT producto.codigo, producto.nombre, producto.precio, fabricante.nombre FROM producto INNER JOIN fabricante ON fabricante.codigo=producto.codigo_fabricante WHERE fabricante.nombre IN ('Asus','Hewlett-Packard','Seagate'); -- Retorna un llistat amb tots els productes dels fabricants Asus, Hewlett-Packardy Seagate. Utilitzant l'operador IN 
SELECT producto.nombre, producto.precio, fabricante.nombre FROM producto INNER JOIN fabricante ON fabricante.codigo=producto.codigo_fabricante WHERE fabricante.nombre LIKE '%e'; -- Retorna un llistat amb el nom i el preu de tots els productes dels fabricants el nom dels quals acabi per la vocal e 
SELECT producto.nombre, producto.precio, fabricante.nombre FROM producto INNER JOIN fabricante ON fabricante.codigo=producto.codigo_fabricante WHERE fabricante.nombre LIKE '%w%'; -- Retorna un llistat amb el nom i el preu de tots els productes el nom de fabricant dels quals contingui el caràcter w en el seu nom 
SELECT producto.nombre, producto.precio, fabricante.nombre FROM producto INNER JOIN fabricante ON fabricante.codigo=producto.codigo_fabricante WHERE producto.precio>=180 ORDER BY producto.precio DESC, producto.nombre; -- Retorna un llistat amb el nom de producte, preu i nom de fabricant, de tots els productes que tinguin un preu major o igual a 180€. Ordeni el resultat en primer lloc pel preu (en ordre descendent) i en segon lloc pel nom (en ordre ascendent) 
SELECT fabricante.codigo, fabricante.nombre FROM fabricante INNER JOIN producto ON producto.codigo_fabricante=fabricante.codigo; -- Retorna un llistat amb el codi i el nom de fabricant, solament d'aquells fabricants que tenen productes associats en la base de dades. 
SELECT fabricante.codigo, fabricante.nombre, producto.nombre, producto.precio FROM fabricante LEFT JOIN producto ON producto.codigo_fabricante=fabricante.codigo; -- Retorna un llistat de tots els fabricants que existeixen en la base de dades, juntament amb els productes que té cadascun d'ells. El llistat haurà de mostrar també aquells fabricants que no tenen productes associats 
SELECT fabricante.codigo, fabricante.nombre FROM fabricante LEFT JOIN producto ON producto.codigo_fabricante=fabricante.codigo WHERE producto.codigo_fabricante is NULL; -- Retorna un llistat on només apareguin aquells fabricants que no tenen cap producte associat 
SELECT * FROM producto , fabricante WHERE producto.codigo_fabricante=fabricante.codigo AND fabricante.nombre = 'Lenovo'; -- Retorna tots els productes del fabricador Lenovo. (Sense utilitzar INNER JOIN). 
SELECT * FROM producto WHERE producto.precio = (SELECT precio FROM producto , fabricante WHERE producto.codigo_fabricante=fabricante.codigo AND fabricante.nombre = 'Lenovo' ORDER BY precio DESC LIMIT 1); -- Retorna totes les dades dels productes que tenen el mateix preu que el producte més car del fabricador Lenovo. (Sense utilitzar INNER JOIN) 
SELECT * FROM producto , fabricante WHERE producto.codigo_fabricante=fabricante.codigo AND fabricante.nombre = 'Lenovo' ORDER BY precio DESC LIMIT 1; -- Llista el nom del producte més car del fabricador Lenovo 
SELECT * FROM producto , fabricante WHERE producto.codigo_fabricante=fabricante.codigo AND fabricante.nombre = 'Hewlett-Packard' ORDER BY precio LIMIT 1; -- Llista el nom del producte més barat del fabricant Hewlett-Packard 
SELECT * FROM producto WHERE producto.precio >= (SELECT precio FROM producto , fabricante WHERE producto.codigo_fabricante=fabricante.codigo AND fabricante.nombre = 'Lenovo' ORDER BY precio DESC LIMIT 1);-- Retorna tots els productes de la base de dades que tenen un preu major o igual al producte més car del fabricador Lenovo 
SELECT * FROM producto INNER JOIN fabricante ON fabricante.codigo=producto.codigo_fabricante WHERE fabricante.nombre = 'Asus' AND producto.precio > (SELECT AVG(precio) FROM producto INNER JOIN fabricante ON fabricante.codigo=producto.codigo_fabricante WHERE fabricante.nombre = 'Asus');  -- Llista tots els productes del fabricador Asus que tenen un preu superior al preu mitjà de tots els seus productes 
SELECT apellido1 AS 'Primer cognom', apellido2 AS 'Segon cognom', nombre AS Nom FROM persona WHERE tipo = 'alumno' ORDER BY apellido1, apellido2, nombre;-- Retorna un llistat amb el primer cognom, segon cognom i el nom de tots els alumnes. El llistat haurà d'estar ordenat alfabèticament de menor a major pel primer cognom, segon cognom i nom
SELECT nombre, apellido1, apellido2 FROM persona WHERE tipo = 'alumno' and telefono IS NULL;-- Esbrina el nom i els dos cognoms dels alumnes que no han donat d'alta el seu número de telèfon en la base de dades
SELECT * FROM persona WHERE tipo = 'alumno' AND fecha_nacimiento between '1999-01-01' AND '1999-12-31';-- Retorna el llistat dels alumnes que van néixer en 1999
SELECT * FROM persona WHERE tipo = 'profesor' AND telefono IS NULL AND nif LIKE '%K';-- Retorna el llistat de professors que no han donat d'alta el seu número de telèfon en la base de dades i a més la seva nif acaba en K
SELECT * FROM asignatura WHERE cuatrimestre = 1 AND curso = 3 AND id_grado = 7;-- Retorna el llistat de les assignatures que s'imparteixen en el primer quadrimestre, en el tercer curs del grau que té l'identificador 7
SELECT persona.apellido1 AS 'Primer cognom', persona.apellido2 AS 'Segon cognom', persona.nombre AS 'Nom', departamento.nombre AS 'Nom departament' FROM persona INNER JOIN profesor ON profesor.id_profesor=persona.id INNER JOIN departamento ON departamento.id = profesor.id_departamento ORDER BY persona.apellido1, persona.apellido2,persona.nombre; -- Retorna un llistat dels professors juntament amb el nom del departament al qual estan vinculats. El llistat ha de retornar quatre columnes, primer cognom, segon cognom, nom i nom del departament. El resultat estarà ordenat alfabèticament de menor a major pels cognoms i el nom
SELECT asignatura.nombre AS 'Nom Asignatures', curso_escolar.anyo_inicio AS 'Any dinici', curso_escolar.anyo_fin AS 'Any de fi' FROM asignatura, curso_escolar, persona, alumno_se_matricula_asignatura WHERE persona.id=alumno_se_matricula_asignatura.id_alumno AND alumno_se_matricula_asignatura.id_curso_escolar=curso_escolar.id AND alumno_se_matricula_asignatura.id_asignatura=asignatura.id AND persona.nif = '26902806M'; -- Retorna un llistat amb el nom de les assignatures, any d'inici i any de fi del curs escolar de l'alumne amb nif 26902806M
SELECT departamento.nombre FROM departamento, profesor, asignatura, grado WHERE departamento.id=profesor.id_departamento AND profesor.id_profesor=asignatura.id_profesor AND asignatura.id_grado=grado.id AND grado.nombre = 'Grado en Ingeniería Informática (Plan 2015)';-- Retorna un llistat amb el nom de tots els departaments que tenen professors que imparteixen alguna assignatura en el Grau en Enginyeria Informàtica (Pla 2015)
SELECT * FROM persona, alumno_se_matricula_asignatura, curso_escolar WHERE persona.id=alumno_se_matricula_asignatura.id_alumno AND alumno_se_matricula_asignatura.id_curso_escolar=curso_escolar.id AND curso_escolar.anyo_inicio = 2018; -- Retorna un llistat amb tots els alumnes que s'han matriculat en alguna assignatura durant el curs escolar 2018/2019
SELECT departamento.nombre AS 'Nom departament', persona.apellido1 AS 'Primer cognom', persona.apellido2 AS 'Segon cognom', persona.nombre AS 'Nom' FROM persona LEFT JOIN profesor ON persona.id=profesor.id_profesor LEFT JOIN departamento ON profesor.id_departamento=departamento.id WHERE persona.tipo='profesor' ORDER BY persona.apellido1, persona.apellido2,persona.nombre;-- Retorna un llistat amb els noms de tots els professors i els departaments que tenen vinculats. El llistat també ha de mostrar aquells professors que no tenen cap departament associat. El llistat ha de retornar quatre columnes, nom del departament, primer cognom, segon cognom i nom del professor. El resultat estarà ordenat alfabèticament de menor a major pel nom del departament, cognoms i el nom
SELECT * FROM persona LEFT JOIN profesor ON persona.id=profesor.id_profesor WHERE persona.tipo='profesor' AND profesor.id_profesor IS NULL; -- Retorna un llistat amb els professors que no estan associats a un departament
SELECT * FROM departamento LEFT JOIN profesor ON profesor.id_departamento=departamento.id WHERE profesor.id_profesor IS NULL;-- Retorna un llistat amb els departaments que no tenen professors associats
SELECT persona.id, persona.nombre FROM persona LEFT JOIN profesor ON persona.id=profesor.id_profesor LEFT JOIN asignatura ON profesor.id_profesor=asignatura.id_profesor WHERE asignatura.id_profesor IS NULL;-- Retorna un llistat amb els professors que no imparteixen cap assignatura
SELECT * FROM asignatura LEFT JOIN profesor ON profesor.id_profesor=asignatura.id_profesor WHERE asignatura.id_profesor IS NULL;-- Retorna un llistat amb les assignatures que no tenen un professor assignat
SELECT departamento.id, departamento.nombre FROM departamento LEFT JOIN profesor ON profesor.id_departamento=departamento.id LEFT JOIN asignatura ON profesor.id_profesor=asignatura.id_profesor WHERE id_departamento IS NULL;-- Retorna un llistat amb tots els departaments que no han impartit assignatures en cap curs escolar
SELECT COUNT(id) AS 'Numero de alumnos' FROM persona WHERE tipo = 'alumno' ;-- Retorna el nombre total d'alumnes que hi ha
SELECT COUNT(id) AS 'Alumnos que nacieron en 1999' FROM persona WHERE fecha_nacimiento BETWEEN '1999-01-01' AND '1999-12-31'; -- Calcula quants alumnes van néixer en 1999S
SELECT departamento.nombre AS 'Nom del dapartament', COUNT(departamento.id) AS 'Nº de professors en aquest departament' FROM departamento INNER JOIN profesor ON departamento.id=profesor.id_departamento GROUP BY profesor.id_departamento ORDER BY COUNT(id);-- Calcula quants professors hi ha en cada departament. El resultat només ha de mostrar dues columnes, una amb el nom del departament i una altra amb el nombre de professors que hi ha en aquest departament. El resultat només ha d'incloure els departaments que tenen professors associats i haurà d'estar ordenat de major a menor pel nombre de professors
SELECT departamento.nombre AS 'Nom del dapartament', COUNT(profesor.id_departamento) AS 'Nº de professors en aquest departament' FROM profesor RIGHT JOIN departamento ON departamento.id=profesor.id_departamento GROUP BY departamento.id HAVING departamento.id >0; -- Retorna un llistat amb tots els departaments i el nombre de professors que hi ha en cadascun d'ells. Tingui en compte que poden existir departaments que no tenen professors associats. Aquests departaments també han d'aparèixer en el llistat
SELECT grado.nombre, COUNT(asignatura.id_grado) FROM asignatura RIGHT JOIN grado ON grado.id=asignatura.id_grado GROUP BY grado.nombre ORDER BY COUNT(asignatura.id_grado) DESC;-- Retorna un llistat amb el nom de tots els graus existents en la base de dades i el nombre d'assignatures que té cadascun. Tingui en compte que poden existir graus que no tenen assignatures associades. Aquests graus també han d'aparèixer en el llistat. El resultat haurà d'estar ordenat de major a menor pel nombre d'assignatures
SELECT grado.nombre, COUNT(asignatura.id_grado) FROM asignatura RIGHT JOIN grado ON grado.id=asignatura.id_grado GROUP BY grado.nombre HAVING COUNT(asignatura.id_grado) > 40;-- Retorna un llistat amb el nom de tots els graus existents en la base de dades i el nombre d'assignatures que té cadascun, dels graus que tinguin més de 40 assignatures associades
SELECT grado.nombre AS 'Nom del grau', asignatura.nombre AS 'Tipus dasignatura', asignatura .creditos AS 'Suma dels credits' FROM asignatura RIGHT JOIN grado ON grado.id=asignatura.id_grado; -- Retorna un llistat que mostri el nom dels graus i la suma del nombre total de crèdits que hi ha per a cada tipus d'assignatura. El resultat ha de tenir tres columnes: nom del grau, tipus d'assignatura i la suma dels crèdits de totes les assignatures que hi ha d'aquest tipus
SELECT curso_escolar.anyo_inicio AS 'Any dinici', COUNT(alumno_se_matricula_asignatura.id_curso_escolar) AS 'Nª alumnes matriculats' FROM alumno_se_matricula_asignatura INNER JOIN curso_escolar ON curso_escolar.id=alumno_se_matricula_asignatura.id_curso_escolar GROUP BY curso_escolar.anyo_inicio; -- Retorna un llistat que mostri quants alumnes s'han matriculat d'alguna assignatura en cadascun dels cursos escolars. El resultat haurà de mostrar dues columnes, una columna amb l'any d'inici del curs escolar i una altra amb el nombre d'alumnes matriculats 
SELECT persona.id AS 'ID', persona.nombre AS 'Nom', persona.apellido1 AS 'Primer Cognom', persona.apellido2 AS 'Segon Cognom' , COUNT(asignatura.id_profesor) AS 'Nª dasignatures' FROM persona LEFT JOIN profesor ON persona.id=profesor.id_profesor LEFT JOIN asignatura ON asignatura.id_profesor=profesor.id_profesor WHERE persona.tipo = 'profesor' GROUP BY persona.id ORDER BY COUNT(asignatura.id_profesor) DESC; -- Retorna un llistat amb el nombre d'assignatures que imparteix cada professor. El llistat ha de tenir en compte aquells professors que no imparteixen cap assignatura. El resultat mostrarà cinc columnes: id, nom, primer cognom, segon cognom i nombre d'assignatures. El resultat estarà ordenat de major a menor pel nombre d'assignatures */
SELECT * FROM persona WHERE tipo='alumno' ORDER BY fecha_nacimiento DESC LIMIT 1; -- Retorna totes les dades de l'alumne més jove
SELECT DISTINCT persona.nombre FROM persona INNER JOIN profesor ON persona.id=profesor.id_profesor LEFT JOIN asignatura ON profesor.id_profesor=asignatura.id_profesor WHERE asignatura.id_profesor IS NULL; -- Retorna un llistat amb els professors que tenen un departament associat i que no imparteixen cap assignatura 